### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/apuleius_the-golden-ass-of-apuleius_william-adlington#1]
**General issues:**

- [x] #5

- [x] #6

- [x] #7

- [x] #9

- [x] #2

**editors-dedication.xhtml:**

- [x] Lint is complaining because the file uses structuring for poems, songs, etc. A more correct way to structure this dedication is like this:
```
		<section id="dedication" epub:type="dedication">
			<p>To<br/>
			<b>Stéphane Mallarmé</b><br/>
			This Metamorphosis of<br/>
			an Ancient Decadent</p>
		</section>
```
Instead of targeting the second `<span>` element you can target the `<b>` for the CSS.

**publishers-introduction.xhtml:**

- [x] "W. A. As" needs to be tagged as an abbreviation.

- [x] Roman numerals are set using uppercase ASCII. You can make this change in an [Editorial] commit. 

- [x] Dramatis personae doesn't need italics.

- [x] I believe "ungles" should be tagged as Latin instead of French.

**translators-dedication.xhtml:**

- [x] "To the Right Honourable and Mighty Lord..." is too long to be the title. The page scans title this section "The Epistle Dedicatory".

- [x] "To the Right Honourable and Mighty Lord..." can be placed inside of a `<header>` element along with the title. 

- [x] This section is not a letter and shouldn't use letter semantics like "se:letter.dateline," "z3998:salutation," "z3998:valediction," or "z3998:sender".

- [x] Typically we stay away from `<small>` elements. Use CSS to enlarge text in other areas.

**tramslators-introduction-2.xhtml:**

- [x] `<i epub:type="se:name.publication.book" xml:lang="la">Books of the Golden Ass</i>` doesn't need the language tag. The title is in English

**authors-preface.xhtml:**

- [x] #10

**chapter-2-11.xhtml:**

- [x] Nilus is the Latin form of Nile, but it doesn't receive italics as it is a proper name ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.2)). You can convert the `<i>` in a `<span>`.

**chapter-3-14.xhtml:**

- [x] Grecia is the Latin form of Greece, but it doesn't receive italics as it is a proper name ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.2)). You can convert the `<i>` in a `<span>`.

**chapter-4-19.xhtml:**

- [x] #3

**chapter-4-20.xhtml:**

- [x] Thracia is the Latin form of Thrace, but it doesn't receive italics as it is a proper name ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.2)). You can convert the `<i>` in a `<span>`.

**chapter-5-22.xhtml:**

- [x] I recommend changing `epub:type="z3998:poem"` to `epub:type="z3998:verse"` in this chapter, because the book states "he gave answer in Latin verse..."

- [x] Sicilie is the Latin form of Sicily, but it doesn't receive italics as it is a proper name ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.2)). You can convert the `<i>` in a `<span>`.

**chapter-3-39.xhtml:**

- [x] "Coniuncti terram proscindunt boves ut in futurum loeta germinent sata" doesn't appear in a separate paragraph in the page scans ([p. 183](https://archive.org/details/goldenassofapule00apuliala/page/183/mode/1up)).

**chapter-3-39.xhtml:**

- [x] "Quorsum vacuum ducis asinum?" doesn't appear in a separate paragraph in the page scans ([p. 200](https://archive.org/details/goldenassofapule00apuliala/page/200/mode/1up)).

**chapter-10-46.xhtml:**

- [x] Grecia is the Latin form of Greece, but it doesn't receive italics as it is a proper name ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.6.4/single-page#8.2.9.2)). You can convert the `<i>` in a `<span>`.

**chapter-11-48.xhtml:**

- [x] #4

**content.opf:**

- [x] Lines 57, 63, and 70 need their properties to be `property="role"`.

**Colophon:**
- [x] #8

**Etc.:**

- Remember to run `se build-title .`, `se build-manifest .`, `se build-spine .`, and `se build-toc .` after fixing the titles, file names, and file ids.

**Comment by kingrpaul** [comment]
I think that's it. Note that I undid the changes to the spine to restore the section break locations.
